### PR TITLE
chore(composer): Adds a script for the post update event

### PR DESCRIPTION
**Pull request by juho-jaakkola**
@ewinslow Is it OK to have a separate class for post-install and post-update?

Alternative would be to use a single class and check whether the event passed in the class constructor is "install" or "update".

### CODE REVIEW

**Comment by ewinslow** [comment]
It's fine for the class to be separate. We just need the hook in place for
future upgrade potential.

On Monday, August 31, 2015, Juho Jaakkola notifications@github.com wrote:

> @ewinslow https://github.com/ewinslow Is it OK to have a separate class
> for post-install and post-update?
> 
> Alternative would be to use a single class and check whether the event
> 
> ## passed in the class constructor is "install" or "update".
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/Elgg/starter-project/pull/25
> Commit Summary
> - chore(composer): Adds a script for the post update event
> 
> File Changes
> - _M_ composer.json
>   https://github.com/Elgg/starter-project/pull/25/files#diff-0 (1)
> 
> Patch Links:
> - https://github.com/Elgg/starter-project/pull/25.patch
> - https://github.com/Elgg/starter-project/pull/25.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Elgg/starter-project/pull/25.

## 

Evan Winslow
http://community.elgg.org/profile/ewinslow

**Comment by juho-jaakkola** [comment]
This now also fixes #15

**Comment by juho-jaakkola** [comment]
The script this is referring to is added in: https://github.com/Elgg/Elgg/pull/8904

**Comment by juho-jaakkola** [comment]
@ewinslow Can you verify that everything is OK after these two PRs get merged?

**Pull request merged**
