### PR TITLE
feature(composer): Check composer.phar into source to make getting started even easier

### LINKED ISSUE #19: Distribute composer.phar with zips of starter-project?
This removes one step from the process of getting up-and-running using composer (namely: the install-composer-wait-what-is-that-where-do-i-get-it step).

### PR DESCRIPTION
**Pull request by ewinslow**
Fixes #19

### CODE REVIEW

**Comment by ewinslow** [comment]
@mrclay @Srokap any thoughts on this?

**Comment by Srokap** [comment]
Would be awesome if we did `curl -sS https://getcomposer.org/installer | php` in release script to make sure it stays up to date. I have no problem with checking it in. It's 270KB, no compatibility issues to be anticipated, so sure, why not.

**Comment by ewinslow** [comment]
How about just `php composer.phar self-update`? But yea, keeping up to date
is good idea.

**Comment by Srokap** [comment]
Curl just sounds more bullet proof, but either way is fine with me.

P.S. Correction, it's 1.1 MB, but still acceptable I guess.

**Comment by ewinslow** [comment]
Closed for lack of activity. Doesn't seem to solve a problem in practice.

**Pull request closed without merging**
